image:
  file: .gitpod.Dockerfile

github:
  prebuilds:    
    master: true    
    branches: true    
    pullRequests: true    
    pullRequestsFromForks: false    
    addCheck: true    
    addComment: false    
    addBadge: false
    
tasks:
  - name: Custosing Workspace
    env:
      AWS_CLI_AUTO_PROMPT: on-partial
    init: |
      # install Python libraries for Flask backend app
      cd $THEIA_WORKSPACE_ROOT/backend-flask
      pip3 install -r requirements.txt
      # install npm libraries for frontend
      cd $THEIA_WORKSPACE_ROOT/frontend-react-js
      npm i
      cd $THEIA_WORKSPACE_ROOT

vscode:
  extensions:
    - 42Crunch.vscode-openapi
    - ms-azuretools.vscode-docker
