AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  #General:
  NamingPrefix:
    Type: String
    Description: The naming prefix for resources created by this template, and exported values that can be referenced by other stacks.
    Default: Cruddur
  VPCIPv4CidrBlock:
    Description: VPC CIDR block for IPv4. Default of 10.0.0.0/16 is recommended for testing.
    Type: String
    Default: 10.0.0.0/16
#VPC
Resources:
  VPC
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VPCIPv4CidrBlock
      EnableDnsHostnames: true
      EnableDnsSupport: true
      InstanceTenancy: default


#IGW
#Route Tables
# subnets - A, B, C